### PR TITLE
Revert "Add service catalog remover job"

### PR DESCRIPTION
**Pull request by shawn-hurley**
Reverts openshift/cluster-svcat-controller-manager-operator#68

### CODE REVIEW

**Comment by shawn-hurley** [comment]
Causing all upgrades to fail:

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1600/pull-ci-openshift-machine-config-operator-master-e2e-gcp-upgrade/1516#1:build-log.txt%3A1248

Need to investigate much like apiserver issue

**Comment by jmrodri** [comment]
/hold
 I think we have a solution with PR #74

**Comment by jmrodri** [comment]
Closing as PR #74 has been merged

**Pull request closed without merging**
