### PR TITLE
Bug 1854978: Remove servicecatalogcontrollermanager CRD

### PR DESCRIPTION
**Pull request by jmrodri**

### CODE REVIEW

**Comment by jwforres** [comment]
@jmrodri so if you've already updated to an earlier 4.5 and then update to the 4.5.z with this fix, is the remover job going to run again and remove the CRDs?

**Comment by jmrodri** [comment]
> @jmrodri so if you've already updated to an earlier 4.5 and then update to the 4.5.z with this fix, is the remover job going to run again and remove the CRDs?

@jwforres no, so once the job exists in 4.5 it will not get re-run in 4.5.z upgrades. Just confirmed with @wking. Which means this bug fix only applies to those folks upgrading from 4.4 to 4.5.z. Now I wonder if it's even worth fixing. Thoughts? I'm leaning towards possibly just adding documentation to explain how to remove the CRDs by hand as the solution the bug.

**Pull request merged**
