### PR TITLE
Bug 1831027: Upgradeable = False, link to OpenShift docs

### PR DESCRIPTION
**Pull request by jmrodri**
The service catalog is deprecated. In OpenShift 4.4, we will block
upgrades to 4.5 or later by setting the Upgradeable field to False.
This PR updates the message to point to the documentation that states
that.

### CODE REVIEW

**Comment by shawn-hurley** [comment]
Overriding valid bug because service catalog is not available in 4.5

**Comment by ashcrow** [comment]
Vendor additions are for the additional test. :+1:

**Pull request merged**
