### PR TITLE
Bug 1737317: backport fix from library-go

### PR DESCRIPTION
**Pull request by jmrodri**
Updating to release-4.1 version of library-go and associated deps.

### CODE REVIEW

**Comment by jmrodri** [comment]
Blocked by https://github.com/openshift/release/pull/5189

**Comment by eparis** [comment]
This changes service cat and the service cat tests are failing. Seems like some digging is required here.

**Comment by jmrodri** [comment]
Bug 1737317 was closed as WONTFIX, closing this PR.

**Pull request closed without merging**
